In [56]:
import pandas as pd

df = pd.read_csv("Final_AQI_Balanced_Dataset.csv")
df.head()

,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg,AQI_Category
0,176.679583,293.727083,16.357500,33.182917,39.324583,10.389583,1.177917,15.869583,11.346250,72.005000,0.710833,174.558750,49.583750,974.870833,Moderate
1,180.665000,293.752500,20.056250,35.415000,44.370417,11.555417,1.162917,17.450000,10.869583,69.444583,0.677500,169.500000,62.596250,974.491667,Moderate
2,191.461250,306.088333,25.389583,38.743750,50.359167,9.502083,1.485000,15.040833,10.237083,79.782500,0.655000,167.399583,46.275417,974.446667,Moderate
3,215.310417,347.739583,28.622917,39.125417,50.938333,10.648333,1.319583,11.795417,10.414167,80.744167,0.767917,200.645000,34.486667,974.443750,Poor
4,159.162500,275.042500,24.269583,39.634583,46.040833,11.218750,1.270833,14.331250,11.354583,81.830833,0.698333,189.891667,27.805833,974.436250,Moderate

In [57]:
df.tail()

,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg,AQI_Category
495,586.498152,659.311335,31.729843,51.059285,55.499271,15.255194,2.214521,29.760681,24.732187,78.404778,0.680237,190.634243,57.968577,963.701254,Severe
496,571.988300,629.313349,33.971877,49.545926,35.255735,14.617839,2.385924,28.363629,24.204462,77.529325,0.705796,194.679159,61.140436,962.810901,Severe
497,410.904046,702.229274,3.845862,52.024544,52.074945,13.998989,2.703408,32.956792,24.919254,81.849385,0.656507,197.854424,61.420218,963.033710,Severe
498,510.148393,551.481660,20.848115,48.293973,46.547960,15.489362,2.513495,30.787819,25.223937,75.096419,0.661409,203.286168,60.163099,961.946576,Severe
499,450.007278,587.518264,50.357062,45.877055,42.624375,15.158260,2.400524,32.747568,24.336505,74.161154,0.667413,194.443312,62.504044,963.599918,Severe

In [58]:
df.shape

(500, 15)

In [59]:
df.info

<bound method DataFrame.info of      PM2.5_µgm³   PM10_µgm³    NO_µgm³   NO2_µgm³    NOx_ppb   SO2_µgm³  \
0    176.679583  293.727083  16.357500  33.182917  39.324583  10.389583
1    180.665000  293.752500  20.056250  35.415000  44.370417  11.555417
2    191.461250  306.088333  25.389583  38.743750  50.359167   9.502083
3    215.310417  347.739583  28.622917  39.125417  50.938333  10.648333
4    159.162500  275.042500  24.269583  39.634583  46.040833  11.218750
..          ...         ...        ...        ...        ...        ...
495  586.498152  659.311335  31.729843  51.059285  55.499271  15.255194
496  571.988300  629.313349  33.971877  49.545926  35.255735  14.617839
497  410.904046  702.229274   3.845862  52.024544  52.074945  13.998989
498  510.148393  551.481660  20.848115  48.293973  46.547960  15.489362
499  450.007278  587.518264  50.357062  45.877055  42.624375  15.158260

      CO_mgm³  Ozone_µgm³       AT_C  RH_percent     WS_ms      WD_deg  \
0    1.177917   15.869583  11.346250   72.005000  0.710833  174.558750
1    1.162917   17.450000  10.869583   69.444583  0.677500  169.500000
2    1.485000   15.040833  10.237083   79.782500  0.655000  167.399583
3    1.319583   11.795417  10.414167   80.744167  0.767917  200.645000
4    1.270833   14.331250  11.354583   81.830833  0.698333  189.891667
..        ...         ...        ...         ...       ...         ...
495  2.214521   29.760681  24.732187   78.404778  0.680237  190.634243
496  2.385924   28.363629  24.204462   77.529325  0.705796  194.679159
497  2.703408   32.956792  24.919254   81.849385  0.656507  197.854424
498  2.513495   30.787819  25.223937   75.096419  0.661409  203.286168
499  2.400524   32.747568  24.336505   74.161154  0.667413  194.443312

       SR_Wmt2     BP_mmHg AQI_Category
0    49.583750  974.870833     Moderate
1    62.596250  974.491667     Moderate
2    46.275417  974.446667     Moderate
3    34.486667  974.443750         Poor
4    27.805833  974.436250     Moderate
..         ...         ...          ...
495  57.968577  963.701254       Severe
496  61.140436  962.810901       Severe
497  61.420218  963.033710       Severe
498  60.163099  961.946576       Severe
499  62.504044  963.599918       Severe

[500 rows x 15 columns]>

In [60]:
df.describe

<bound method NDFrame.describe of      PM2.5_µgm³   PM10_µgm³    NO_µgm³   NO2_µgm³    NOx_ppb   SO2_µgm³  \
0    176.679583  293.727083  16.357500  33.182917  39.324583  10.389583
1    180.665000  293.752500  20.056250  35.415000  44.370417  11.555417
2    191.461250  306.088333  25.389583  38.743750  50.359167   9.502083
3    215.310417  347.739583  28.622917  39.125417  50.938333  10.648333
4    159.162500  275.042500  24.269583  39.634583  46.040833  11.218750
..          ...         ...        ...        ...        ...        ...
495  586.498152  659.311335  31.729843  51.059285  55.499271  15.255194
496  571.988300  629.313349  33.971877  49.545926  35.255735  14.617839
497  410.904046  702.229274   3.845862  52.024544  52.074945  13.998989
498  510.148393  551.481660  20.848115  48.293973  46.547960  15.489362
499  450.007278  587.518264  50.357062  45.877055  42.624375  15.158260

      CO_mgm³  Ozone_µgm³       AT_C  RH_percent     WS_ms      WD_deg  \
0    1.177917   15.869583  11.346250   72.005000  0.710833  174.558750
1    1.162917   17.450000  10.869583   69.444583  0.677500  169.500000
2    1.485000   15.040833  10.237083   79.782500  0.655000  167.399583
3    1.319583   11.795417  10.414167   80.744167  0.767917  200.645000
4    1.270833   14.331250  11.354583   81.830833  0.698333  189.891667
..        ...         ...        ...         ...       ...         ...
495  2.214521   29.760681  24.732187   78.404778  0.680237  190.634243
496  2.385924   28.363629  24.204462   77.529325  0.705796  194.679159
497  2.703408   32.956792  24.919254   81.849385  0.656507  197.854424
498  2.513495   30.787819  25.223937   75.096419  0.661409  203.286168
499  2.400524   32.747568  24.336505   74.161154  0.667413  194.443312

       SR_Wmt2     BP_mmHg AQI_Category
0    49.583750  974.870833     Moderate
1    62.596250  974.491667     Moderate
2    46.275417  974.446667     Moderate
3    34.486667  974.443750         Poor
4    27.805833  974.436250     Moderate
..         ...         ...          ...
495  57.968577  963.701254       Severe
496  61.140436  962.810901       Severe
497  61.420218  963.033710       Severe
498  60.163099  961.946576       Severe
499  62.504044  963.599918       Severe

[500 rows x 15 columns]>

In [61]:
df.isnull().sum()

PM2.5_µgm³      0
PM10_µgm³       0
NO_µgm³         0
NO2_µgm³        0
NOx_ppb         0
SO2_µgm³        0
CO_mgm³         0
Ozone_µgm³      0
AT_C            0
RH_percent      0
WS_ms           0
WD_deg          0
SR_Wmt2         0
BP_mmHg         0
AQI_Category    0
dtype: int64

In [62]:
df.dtypes

PM2.5_µgm³      float64
PM10_µgm³       float64
NO_µgm³         float64
NO2_µgm³        float64
NOx_ppb         float64
SO2_µgm³        float64
CO_mgm³         float64
Ozone_µgm³      float64
AT_C            float64
RH_percent      float64
WS_ms           float64
WD_deg          float64
SR_Wmt2         float64
BP_mmHg         float64
AQI_Category     object
dtype: object

In [63]:
#checking for negative values
(df.select_dtypes(include=[np.number]) < 0).sum()

PM2.5_µgm³    0
PM10_µgm³     0
NO_µgm³       0
NO2_µgm³      0
NOx_ppb       0
SO2_µgm³      0
CO_mgm³       0
Ozone_µgm³    0
AT_C          0
RH_percent    0
WS_ms         0
WD_deg        0
SR_Wmt2       0
BP_mmHg       0
dtype: int64

In [64]:
#check balancing ]
df['AQI_Category'].value_counts()

AQI_Category
Satisfactory    143
Good             97
Moderate         80
Poor             60
Very Poor        60
Severe           60
Name: count, dtype: int64

In [65]:
#duplicate rows 
df.duplicated().sum()

np.int64(0)

In [66]:
df.describe()

,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,179.873010,299.796260,34.334684,46.932502,55.023408,15.089964,1.592617,33.077257,24.656170,65.124943,0.897296,177.868774,96.270431,963.101011
std,154.181169,185.975126,25.087780,16.086776,27.259736,3.294837,0.665983,10.398412,7.833411,14.238274,0.319788,17.785809,38.445649,5.223221
min,11.939167,32.949167,0.000000,20.477500,21.706250,7.330621,0.724583,2.415195,0.000000,31.724583,0.428794,136.238750,18.496250,946.815833
25%,61.789687,155.834167,16.345521,33.769469,33.666059,12.414687,1.025104,27.073145,17.888315,56.593958,0.671023,163.470772,62.492106,960.711667
50%,108.574583,259.027917,24.708542,45.989647,47.053750,14.967700,1.335625,31.367719,25.674490,69.867543,0.789792,179.466222,87.038125,963.403125
75%,282.021464,435.851637,46.256250,55.133437,68.544484,16.919500,2.248958,36.601458,30.824583,75.682500,1.060833,191.537813,126.167187,965.479738
max,757.707930,923.253359,141.116369,109.855728,156.888320,29.004583,3.890952,71.935833,40.794433,91.177917,2.405833,222.628907,185.500833,982.230000

In [67]:
#till now our dataset is good ready for training